trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      mkdir copyrepo
      $alias = 'Wariorek:â€™+ "$(Github.PAT)"
      $destURL = 'https://$(AzureDevOps.PAT)@marcinmmazurek.visualstudio.com/MyFirstProject/_git/GithubIntegrationTest'
      $sourceURL = 'https://' + $alias + '@github.com/Wariorek/MyIdolSpring.git'
      Set-Location "$(Build.SourcesDirectory)/copyrepo"
      git clone --mirror $sourceURL
      Set-Location "$(Build.SourcesDirectory)/copyrepo/$(GITLABREPONAME)/"
      Write-Host "*****Git removing remote origin****"
      git remote rm origin
      Write-Output "*****Git remote add****"
      git remote add --mirror=fetch origin $destURL
      Write-Output "*****Git fetch origin****"
      git fetch $sourceURL
      Write-Output "*****Git push to Azure Repos****"
      git push origin --all -f
